### ISSUE TITLE
Consider implementing the Into trait

### ISSUE THREAD

**Issue by matpb** [the-denom/token-factory-cosmwasm#2]
Would it be possible to implement the `Into` trait on all msg types, and not just `From`?
I'm running into some issues where adding a NoriaMsg to a list of messages in a call will mess up the response of the execute message (and it feels inefficient to rework 20+ execute messages just for adding a single NoriaMsg somewhere).

**Comment by 0xForerunner** [comment]
As discussed on discord not sure this is possible.
